# save_baseline.py — Baseline Hash Storage
# Runs on Raspberry Pi Pico W
# Stores the known-good SHA-256 hash of clean ESP32 firmware
# Run this ONCE after establishing clean firmware baseline
# Never run again unless intentionally updating the baseline

# Known-good SHA-256 hash of clean ESP32 firmware
# Generated by ESP32 internally using mbedtls SHA-256
# Over first 0x11000 bytes of flash memory
baseline_hash = "a39a77fd06cac152f6ca696cdfc13c8998a6433eec3250e964012c197ab0b037"

# Store permanently in Pico W flash memory
with open("baseline.txt", "w") as f:
    f.write(baseline_hash)

print("Baseline hash saved successfully!")
print("Hash:", baseline_hash)
print("Stored in: baseline.txt")
